### ISSUE TITLE
git plugin race condition on bot startup

### ISSUE THREAD

**Issue by melwil** [dotkom/OnlineGuru#13]
Sometimes produces an error which I believe to be a race condition on dependency initialization and dependency injecting. Needs some investigation.

Exception in thread "OnlineGuru" java.lang.NullPointerException
        at com.google.inject.BindingBuilderImpl$ImplicitImplementation.get(BindingBuilderImpl.java:334)
        at com.google.inject.InjectorImpl$9$1.call(InjectorImpl.java:708)
        at com.google.inject.InjectorImpl.callInContext(InjectorImpl.java:747)
        at com.google.inject.InjectorImpl$9.get(InjectorImpl.java:702)
        at com.google.inject.InjectorImpl.getInstance(InjectorImpl.java:728)
        at no.ntnu.online.onlineguru.plugin.plugins.git.Git.registerWithXmlRpcServer(Git.java:74)
        at no.ntnu.online.onlineguru.plugin.plugins.git.Git.addWand(Git.java:59)
        at no.ntnu.online.onlineguru.plugin.control.PluginManager.initiatePlugin(PluginManager.java:112)
        at no.ntnu.online.onlineguru.plugin.control.PluginManager.loadPlugins(PluginManager.java:68)
        at no.ntnu.online.onlineguru.plugin.control.PluginManager.<init>(PluginManager.java:50)
        at no.ntnu.online.onlineguru.OnlineGuru$1.run(OnlineGuru.java:47)

**Comment by melwil** [comment]
Fixed in the github plugin.
